# Generated by Django 4.0.5 on 2022-06-18 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assigment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "question_paper",
                    models.FileField(
                        upload_to="stuff_upload", verbose_name="Question Paper"
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                ("description", models.TextField(null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="assigment",
                        to="core.subjects",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assigment",
                "verbose_name_plural": "Assigments",
                "db_table": "assigment",
            },
        ),
        migrations.CreateModel(
            name="AnswerPaper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("name", models.CharField(max_length=250)),
                (
                    "answer_paper",
                    models.FileField(
                        upload_to="student_upload", verbose_name="Answer Paper"
                    ),
                ),
                (
                    "submited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AnswerPaper",
                "verbose_name_plural": "AnswerPapers",
                "db_table": "answer_paper",
            },
        ),
    ]
